Ticket_Agency/ClientWebService/Controllers/DepartureController.cs
using Common.DTO;
using Common.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Threading.Tasks;
using Common.Enums;
using Common.DTO.Weather;

namespace ClientWebService.Controllers
{
    public class DepartureController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateDeparture()
        {
            ViewBag.enumList = new List<TransportType>() { TransportType.BUS, TransportType.PLANE, TransportType.TRAIN };

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateDeaprture(Departure departure)
        {
            var binding = new NetTcpBinding(SecurityMode.None);
            var endpointAddress = new EndpointAddress("net.tcp://localhost:19999/WebCommunication");

            using (var channelFactory = new ChannelFactory<IValidatorService>(binding, endpointAddress))
            {
                IValidatorService validator = null;
                try
                {
                    validator = channelFactory.CreateChannel();
                    await validator.CreateDeparture(departure);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }

            //wait for pab sub to get status of registration

            return Redirect("/");
        }

        [HttpPost]
        public async Task<IActionResult> FilterDeparture(string transportType, DateTime fromDate, int availableTickets)
        {
            ViewBag.logged = HttpContext.Session.GetString("Logged");
            List<Departure> departureList = new List<Departure>();
            Dictionary<long, WeatherData> weatherDatas = new Dictionary<long, WeatherData>();

            var binding = new NetTcpBinding(SecurityMode.None);
            var endpointAddress = new EndpointAddress("net.tcp://localhost:19999/WebCommunication");

            using (var channelFactory = new ChannelFactory<IValidatorService>(binding, endpointAddress))
            {
                IValidatorService validator = null;
                try
                {
                    validator = channelFactory.CreateChannel();
                    departureList = await validator.ListDepartureFilter(transportType, fromDate, availableTickets);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }

            foreach (var departure in departureList)
            {
                var weatherData = await GetWeatherData(departure.CityName);
                weatherDatas.Add(departure.ID, weatherData);
            }

            ViewBag.WeatherData = weatherDatas;

            return View("ListDeparture", departureList);
        }


        [HttpPost]
        public async Task<IActionResult> SortDeparture(string sortBy, string direction)
        {
            ViewBag.logged = HttpContext.Session.GetString("Logged");
            List<Departure> departureList = new List<Departure>();
            Dictionary<long, WeatherData> weatherDatas = new Dictionary<long, WeatherData>();

            var binding = new NetTcpBinding(SecurityMode.None);
            var endpointAddress = new EndpointAddress("net.tcp://localhost:19999/WebCommunication");

            using (var channelFactory = new ChannelFactory<IValidatorService>(binding, endpointAddress))
            {
                IValidatorService validator = null;
                try
                {
                    validator = channelFactory.CreateChannel();
                    departureList = await validator.ListDepartureSort(sortBy, direction);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }

            foreach (var departure in departureList)
            {
                var weatherData = await GetWeatherData(departure.CityName);
                weatherDatas.Add(departure.ID, weatherData);
            }

            ViewBag.WeatherData = weatherDatas;

            return View("ListHistoryDeparture", departureList);
        }


        public async Task<IActionResult> ListDeparture()
        {
            ViewBag.logged = HttpContext.Session.GetString("Logged");


            var binding = new NetTcpBinding(SecurityMode.None);
            var endpointAddress = new EndpointAddress("net.tcp://localhost:19999/WebCommunication");
            List<Departure> departureList = new List<Departure>();
            Dictionary<long, WeatherData> weatherDatas = new Dictionary<long, WeatherData>();

            using (var channelFactory = new ChannelFactory<IValidatorService>(binding, endpointAddress))
            {
                IValidatorService validator = null;
                try
                {
                    validator = channelFactory.CreateChannel();
                    departureList = await validator.ListDeparture();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }

            foreach (var departure in departureList)
            {
                var weatherData = await GetWeatherData(departure.CityName);
                weatherDatas.Add(departure.ID, weatherData);
            }

            ViewBag.WeatherData = weatherDatas;

            return View(departureList);
        }


        public async Task<IActionResult> ListHistoryDeparture()
        {
            ViewBag.logged = HttpContext.Session.GetString("Logged");

            var binding = new NetTcpBinding(SecurityMode.None);
            var endpointAddress = new EndpointAddress("net.tcp://localhost:19999/WebCommunication");
            List<Departure> departureList = new List<Departure>();
            Dictionary<long, WeatherData> weatherDatas = new Dictionary<long, WeatherData>();

            using (var channelFactory = new ChannelFactory<IValidatorService>(binding, endpointAddress))
            {
                IValidatorService validator = null;
                try
                {
                    validator = channelFactory.CreateChannel();
                    departureList = await validator.ListHistoryDeparture();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }

            foreach (var departure in departureList)
            {
                var weatherData = await GetWeatherData(departure.CityName);
                weatherDatas.Add(departure.ID, weatherData);
            }

            ViewBag.WeatherData = weatherDatas;

            return View(departureList);
        }


        private async Task<WeatherData> GetWeatherData(string cityName)
        {
            WeatherData weatherData = new WeatherData();

            var binding = new NetTcpBinding(SecurityMode.None);
            var endpointAddress = new EndpointAddress("net.tcp://localhost:20045/WeatherService");

            using (var channelFactory = new ChannelFactory<IWeatherService>(binding, endpointAddress))
            {
                IWeatherService weather = null;
                try
                {
                    weather = channelFactory.CreateChannel();
                    weatherData = await weather.GetWeatherData(cityName);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }

            return weatherData;
        }

        [HttpPost]
        public async Task<IActionResult> BuyDepertureTicket(long id, int amount)
        {
            var logged = HttpContext.Session.GetString("Logged");
            ViewBag.logged = logged;

            if (logged == null || logged == "")
                return RedirectToAction("Index", "Home");

            var binding = new NetTcpBinding(SecurityMode.None);
            var endpointAddress = new EndpointAddress("net.tcp://localhost:19999/WebCommunication");
            List<Departure> departureList = new List<Departure>();

            using (var channelFactory = new ChannelFactory<IValidatorService>(binding, endpointAddress))
            {
                IValidatorService validator = null;
                try
                {
                    validator = channelFactory.CreateChannel();
                    await validator.BuyDepertureTicket(logged, id, amount);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }

            //get from pub sub

            return RedirectToAction("UserPurchaseList", "User");
        }
    }
}

Ticket_Agency/ClientWebService/Views/Departure/CreateDeparture.cshtml
@model Common.DTO.Departure

@{
    ViewData["Title"] = "CreateDeparture";
}

<h2>Create Departure</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateDeaprture">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TransportType" class="control-label"></label>
                @Html.DropDownListFor(model => model.TransportType, new SelectList(ViewBag.enumList))
                @Html.ValidationMessageFor(model => model.TransportType)
                <span asp-validation-for="TransportType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityName" class="control-label"></label>
                <input asp-for="CityName" class="form-control" />
                <span asp-validation-for="CityName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureStart" class="control-label"></label>
                <input asp-for="DepartureStart" class="form-control" />
                <span asp-validation-for="DepartureStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureReturn" class="control-label"></label>
                <input asp-for="DepartureReturn" class="form-control" />
                <span asp-validation-for="DepartureReturn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeaprtureTicketCount" class="control-label"></label>
                <input asp-for="DeaprtureTicketCount" class="form-control" />
                <span asp-validation-for="DeaprtureTicketCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ticket_Agency/ClientWebService/Views/Departure/ListDeparture.cshtml
@model IEnumerable<Common.DTO.Departure>

@{
    ViewData["Title"] = "Departure List";
}

<h2>Departure List</h2>

@using (Html.BeginForm("FilterDeparture", "Departure", FormMethod.Post))
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    <label for="TransportType">Transport Type:</label>
                </th>
                <th>
                    <label for="FromDate">From Date</label>
                </th>
                <th>
                    <label for="AvailableTickets">Available Tickets</label>
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <select id="TransportType" name="TransportType" class="form-control">
                        <option value="">All</option>
                        <option value="BUS">Bus</option>
                        <option value="PLANE">Plane</option>
                        <option value="TRAIN">Train</option>
                    </select>
                </td>
                <td>
                    <input type="date" id="FromDate" name="FromDate" min="@DateTime.Now" class="form-control" />
                </td>
                <td>
                    <input type="number" id="AvailableTickets" name="AvailableTickets" min="0" class="form-control" />
                </td>
                <td>
                    <input type="submit" value="Filter" class="btn btn-default" />
                </td>
            </tr>
        </tbody>
    </table>
}

@using (Html.BeginForm("ListDeparture", "Departure", FormMethod.Get))
{
    <input type="submit" value="Reset" class="btn btn-default" />
}


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TransportType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CityName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureReturn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeaprtureTicketCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureAvaiableTicketCount)
            </th>
            <th>
                Temperature
            </th>
            <th>
                Weather Condition
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TransportType)
                </td>
                <th>
                    @Html.DisplayFor(modelItem => item.CityName)
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureReturn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeaprtureTicketCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureAvaiableTicketCount)
                </td>
                <td>
                    @ViewBag.WeatherData[item.ID].Temperature
                </td>
                <td>
                    <img src=" @ViewBag.WeatherData[item.ID].IconLocation" alt="No image"/>                 
                </td>
                @if (ViewBag.logged != null)
                {
                    @using (Html.BeginForm("BuyDepertureTicket", "Departure", FormMethod.Post))
                    {
                        <td>
                            <input type="hidden" value="@item.ID" name="id" />
                            <input type="number" value="0" name="amount" class="form-control" />
                        </td>
                        <td>
                            <input type="submit" value="Buy" class="btn btn-default" />
                        </td>
                    }
                }
            </tr>
        }
    </tbody>
</table>

Ticket_Agency/ClientWebService/Views/Departure/ListHistoryDeparture.cshtml
@model IEnumerable<Common.DTO.Departure>

@{
    ViewData["Title"] = "HistoryDepartures";
}

<h2>History Departures</h2>


@using (Html.BeginForm("SortDeparture", "Departure", FormMethod.Post))
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    <label for="sortBy">Sort By:</label>
                </th>
                <th>
                    <label for="direction">Direction:</label>
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <select id="sortBy" name="sortBy" class="form-control">
                        <option value="">All</option>
                        <option value="DATE">Departure date</option>
                        <option value="TICKET">Ticket left</option>
                    </select>
                </td>
                <td>
                    <select id="direction" name="direction" class="form-control">
                        <option value="">All</option>
                        <option value="UP">Less first</option>
                        <option value="DOWN">Less last</option>
                    </select>
                </td>
                <td>
                    <input type="submit" value="Sort" class="btn btn-default" />
                </td>
            </tr>
        </tbody>
    </table>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CityName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TransportType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureReturn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeaprtureTicketCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureAvaiableTicketCount)
            </th>
            <th>
                Temperature
            </th>
            <th>
                Weather Condition
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CityName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TransportType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureReturn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeaprtureTicketCount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartureAvaiableTicketCount)
                </td>
                <td>
                    @ViewBag.WeatherData[item.ID].Temperature
                </td>
                <td>
                    <img src=" @ViewBag.WeatherData[item.ID].IconLocation" alt="No image" />
                </td>
            </tr>
        }
    </tbody>
</table>